Repository hassio-addons/addon-grocy, pull requests merged in 2021-12, with the labels that each got.

#262 Upgrades Grocy to 3.1.3
  grocy/Dockerfile
Labels: dependencies

#263 :rocket: Update CI to latest version
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#266 ⬆️ Upgrades php8 to 8.0.14-r0
  grocy/Dockerfile
Labels: dependencies

#267 Apply location fix only when using Ingress
  grocy/rootfs/patches/fix_braindamage.patch
Labels: bugfix
