Repository hassio-addons/addon-grocy, pull requests merged in 2021-04, with the labels that each got.

#155 ⬆️ Upgrades add-on base image to v9.1.6
  grocy/Dockerfile
  grocy/build.json
Labels: dependencies

#156 Make NGinx doing less log spam
  grocy/rootfs/etc/nginx/nginx.conf
Labels: refactor

#157 Fix Grocy current relative URL handling brain-damage
  grocy/Dockerfile
  grocy/rootfs/etc/cont-init.d/grocy.sh
  grocy/rootfs/patches/fix_braindamage.patch
Labels: bugfix, minor

#151 Implement feature setting stock count opened products against minimum stock amount
  grocy/DOCS.md
  grocy/config.json
  grocy/rootfs/etc/services.d/php-fpm/run
Labels: new-feature

#165 Upgrades add-on base image to v9.2.0
  grocy/Dockerfile
  grocy/build.json
Labels: dependencies

#166 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#170 ⬆️ Upgrades composer to 2.0.13-r0
  grocy/Dockerfile
Labels: dependencies
