Repository hassio-addons/addon-grocy, pull requests merged in 2021-11, with the labels that each got.

#244 ⬆️ Upgrades php8 to 8.0.12-r0
  grocy/Dockerfile
Labels: dependencies

#245 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#246 Migrate JSON config to YAML
  grocy/build.json
  grocy/build.yaml
  grocy/config.json
  grocy/config.yaml
Labels: refactor

#247 ⬆️ Upgrades add-on base image to 10.2.0
  grocy/Dockerfile
  grocy/build.yaml
Labels: dependencies

#251 ⬆️ Upgrades add-on base image to 10.2.2
  grocy/Dockerfile
  grocy/build.yaml
Labels: dependencies

#248 Upgrades Grocy to 3.1.2
  grocy/Dockerfile
Labels: dependencies

#257 ⬆️ Upgrades add-on base image to 11.0.0
  grocy/Dockerfile
  grocy/build.yaml
Labels: dependencies, minor

#253 Add missing php8-iconv package
  grocy/Dockerfile
Labels: bugfix

#256 Allow non-administrator HA users to see Grocy
  grocy/config.yaml
Labels: enhancement

#254 Fix issue #208
  grocy/rootfs/patches/fix_braindamage.patch
Labels: bugfix
