Repository hassio-addons/addon-grocy, pull requests merged in 2021-01, with the labels that each got.

#111 Upgrades add-on base image to v9.0.1
  grocy/Dockerfile
  grocy/build.json
  grocy/config.json
Labels: dependencies

#113 Upgrades Grocy to v3.0.1
  grocy/Dockerfile
  grocy/config.json
Labels: dependencies

#114 Upgrade add-on base image to 9.1.0
  grocy/Dockerfile
  grocy/build.json
Labels: dependencies

#115 Refactor NGINX/PHP-FPM configuration
  grocy/config.json
  grocy/rootfs/etc/cont-init.d/nginx.sh
  grocy/rootfs/etc/cont-init.d/php-fpm.sh
  grocy/rootfs/etc/nginx/includes/resolver.conf
  grocy/rootfs/etc/nginx/nginx.conf
  grocy/rootfs/etc/nginx/servers/.gitkeep
  grocy/rootfs/etc/nginx/servers/ingress.conf
  grocy/rootfs/etc/nginx/templates/direct.gtpl
  grocy/rootfs/etc/nginx/templates/ingress.gtpl
  grocy/rootfs/etc/php7/php-fpm.d/.gitkeep
  grocy/rootfs/etc/php7/php-fpm.d/www.conf
  grocy/rootfs/etc/php7/templates/php-fpm.gtpl
Labels: refactor

#116 Fix NGINX waiting for non-activated FPM
  grocy/rootfs/etc/services.d/nginx/run
Labels: bugfix

#119 Remove obsolete webui from configuration
  grocy/config.json
Labels: maintenance

#121 Add languages: cs, el_GR, fi, he_IL, ja, ko_KR, zh_CN, zh_TW
  grocy/DOCS.md
  grocy/config.json
Labels: new-feature

#122 Upgrade add-on base image to 9.1.1
  grocy/Dockerfile
  grocy/build.json
Labels: dependencies

#125 :arrow_up: Upgrades composer to 2.0.9-r0
  grocy/Dockerfile
Labels: dependencies
