Repository hassio-addons/addon-grocy, pull requests merged in 2022-03, with the labels that each got.

#287 ⬆️ Upgrades php8 to 8.0.16-r0
  grocy/Dockerfile
Labels: dependencies

#288 ⬆️ Upgrades add-on base image to 11.1.0
  grocy/Dockerfile
  grocy/build.yaml
Labels: dependencies

#289 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  grocy/build.yaml
  grocy/config.yaml
Labels: enhancement

#290 :lock: Pass sign token to main workflow
  .github/workflows/deploy.yaml
Labels: ci

#291 :books: Add My buttons to documentation
  grocy/DOCS.md
Labels: documentation

#284 ⬆️ Update Grocy to v3.2.0
  grocy/DOCS.md
  grocy/Dockerfile
  grocy/config.yaml
  grocy/rootfs/patches/fix_braindamage.patch
Labels: dependencies

#292 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  grocy/.README.j2
  grocy/DOCS.md
Labels: maintenance
