Repository hassio-addons/addon-grocy, pull requests merged in 2022-06, with the labels that each got.

#297 ⬆️ Upgrades Grocy to 3.3.0
  grocy/Dockerfile
Labels: dependencies, minor

#299 :books: Use new My Home Assistant link format
  grocy/DOCS.md
Labels: documentation

#301 :ambulance: Fix Grocy startup issues
  grocy/Dockerfile
  grocy/rootfs/etc/cont-init.d/grocy.sh
  grocy/rootfs/etc/fix-attrs.d/01-grocy
  grocy/rootfs/etc/php8/templates/php-fpm.gtpl
  grocy/rootfs/etc/services.d/php-fpm/run
Labels: bugfix

#303 ⬆️ Upgrades php8 to 8.0.20-r0
  grocy/Dockerfile
Labels: dependencies

#302 ⬆️ Upgrades Grocy to 3.3.1
  grocy/Dockerfile
Labels: dependencies
