Repository hassio-addons/addon-grocy, pull requests merged in 2023-03, with the labels that each got.

#339 ⬆️ Upgrades add-on base image to 13.1.3
  grocy/Dockerfile
  grocy/build.yaml
Labels: dependencies

#341 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  grocy/Dockerfile
Labels: maintenance

#349 Fixed broken link
  grocy/DOCS.md
Labels: documentation

#350 Update URL
  grocy/DOCS.md
Labels: documentation
